#!/bin/bash

OLD=$(stty -g)
stty raw -echo opost
trap 'stty "$OLD"' EXIT

SCRIPT="$(dirname $0)/emacsrepl.el"
run_repl () {
  emacs -Q --batch --load "$SCRIPT"
  pkill -P $$ -x od
}

stdbuf -oL od -w1 -An -tx1 -v | sed -u -e 's/^ //' | run_repl
