#!/bin/sh
# emacsrepl - Interactive CLI REPL for Emacs Lisp

script=${0%/*}/emacsrepl.el

repl() {
    emacs -Q --batch --load "$script"
    pkill -u "$USER" -P "$$" -x od
}

if [[ "$TERM" == dumb || "$TERM" == cons25 || "$TERM" == emacs ]]; then
    emacs -Q --batch --load "$script"
else
    trap 'stty "$restore"' EXIT

    restore=$(stty -g)
    stty raw -echo opost

    stdbuf -oL od -w1 -An -tx1 -v | repl
fi
