#!/bin/bash
# emacsrepl - Interactive CLI REPL for Emacs Lisp

scriptdir=${0%/*}

repl() {
    emacs -Q --batch -L . --load "$scriptdir/emacsrepl.el"
    pkill -u "$USER" -P "$$" -x od
}

case $TERM in
    dumb|cons25|emacs)
        emacs -Q --batch -L . --load "$scriptdir/emacsrepl.el"
        ;;
    *)
        trap 'stty "$restore"' EXIT

        restore=$(stty -g)
        stty raw -echo opost

        stdbuf -oL od -w1 -An -tx1 -v | repl
esac
